add_newline = true

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[git_status]
conflicted = "âš”ï¸ "
ahead = "ğŸï¸ ğŸ’¨X${count}"
behind = "ğŸ¢X${count}"
diverged = "ğŸ”± ğŸï¸ ğŸ’¨X${ahead_count} ğŸ¢X${behind_count}"
untracked = "ğŸ›¤ï¸"
stashed = "ğŸ“¦"
modified = "ğŸ“"
style = "bright-white"
format = "$all_status$ahead_behind"